title: Patterns Jekyll
baseurl: /sustainability-dashboard

search: True

# Prose configuration
# set ignore parameter to hide files we don't want available to edit
prose:
  rooturl: "_data"
  ignore: ['/css', '/_includes', '/_layouts', '/scripts', '/', '*.yml']
