title: Greenworks Dashboard
baseurl: /greenworks-dashboard

search: False

# Prose configuration
# set ignore parameter to hide files we don't want available to edit
# in this case, we'll hide everything except '/_data'
#prose:
#  rooturl: "_"
#  ignore: ['/css', '/_includes', '/_layouts', '/scripts', '*.yml']
